[general]
background=""

[text.title]
content=""
font.size=12
font.family=""
pos.x=0
pos.y=0

[text.relator]
content=""
font.size=12
font.family=""
pos.x=0
pos.y=0

[deskshare]
width=640
height=480
pos.x=0
pos.y=0

[webcam]
width=1280
height=720
pos.x=0
pos.y=0



